package panoptiumtech.panoptium.utils.pdfReport.entities.report;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.lowagie.text.pdf.draw.LineSeparator;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

public abstract class BasePdfReport {

    protected Document document;
    protected ByteArrayOutputStream outputStream;
    protected PdfWriter writer;

    public byte[] generate(String reportTitle) {
        try {
            outputStream = new ByteArrayOutputStream();
            document = new Document(PageSize.A4, 50, 50, 50, 50);
            writer = PdfWriter.getInstance(document, outputStream);
            document.open();

            addHeader(reportTitle);
            addContent();
            addFooter();

            document.close();
            return outputStream.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Report generation error", e);
        }
    }

    private void addHeader(String title) throws DocumentException {
        Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD, new Color(0, 102, 204)); // синий
        Font dateFont = new Font(Font.HELVETICA, 10, Font.ITALIC, Color.DARK_GRAY);

        Paragraph header = new Paragraph(title, titleFont);
        header.setAlignment(Element.ALIGN_CENTER);
        document.add(header);

        String date = new SimpleDateFormat("dd.MM.yyyy HH:mm").format(new Date());
        Paragraph dateP = new Paragraph("Creation date: " + date, dateFont);
        dateP.setAlignment(Element.ALIGN_RIGHT);
        dateP.setSpacingAfter(20);
        document.add(dateP);
        LineSeparator line = new LineSeparator();
        line.setOffset(-5);
        document.add(new Chunk(line));
    }

    protected abstract void addContent() throws DocumentException;

    private void addFooter() throws DocumentException {
        LineSeparator line = new LineSeparator();
        line.setOffset(-5);
        document.add(new Chunk(line));

        Font footerFont = new Font(Font.HELVETICA, 9, Font.ITALIC, Color.GRAY);
        Paragraph footer = new Paragraph("Generated by Panoptium 2025", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(30);
        document.add(footer);
    }
}
